#
# Copyright (C) 2016-2019  Irotsoma, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#

spring:
  mustache:
    expose-request-attributes: true
management.endpoints.web:
  expose: "*"
# The below versions must match the versions of the libraries included in the package
filecontroller.webui:
  dependencies:
    bootstrapVersion: 4.2.1
    jqueryVersion: 3.3.1-1
# menuLayout list is the top level menu items, menuItems lists are sub menu items (only these two levels are supported)
# for each item under menuLayout or menuItems list:
#   nameProperty should be a property from the internationalization messages for the name of this menu/menu item
#   path should be the path that clicking on this menu/menu item links to
#   validUserRoles is a list of roles allowed to access this link (otherwise menu/menu item is disabled in browser)
#   menuItems contains a list of sub menu items with the same properties as menuLayout list items (only valid for top level menuLayout list)
filecontroller.webui.menus:
  menuLayout:
    - nameProperty: home.label
      path: /
      validUserRoles:
    - nameProperty: users.label
      validUserRoles:
      menuItems:
        - nameProperty: logIn.label
          path: /login
          validUserRoles:
        - nameProperty: logOut.label
          path: /logout
          validUserRoles:
            - ROLE_USER
            - ROLE_ADMIN
        - nameProperty: userDetails.label
          path: /userinfo
          validUserRoles:
            - ROLE_USER
            - ROLE_ADMIN
        - nameProperty: newUser.label
          path: /newuser
          validUserRoles:
            - ROLE_ADMIN
    - nameProperty: cloudServices.label
      validUserRoles:
        - ROLE_USER
        - ROLE_ADMIN
      menuItems:
        - nameProperty: list.label
          path: /cloudserviceslist
          validUserRoles:
        - nameProperty: logIn.label
          path: /cloudserviceslogin
          validUserRoles:
            - ROLE_USER
            - ROLE_ADMIN

