#
# Copyright (C) 2016-2019  Irotsoma, LLC
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#

spring:
  mustache:
    expose-request-attributes: true
filecontroller.webui:
  dependencies:
    bootstrapVersion: 4.2.1
    jqueryVersion: 3.3.1-1
filecontroller.webui.menus:
  menuLayout:
    - nameProperty: home.label
      path: /
      validUserRoles:
    - nameProperty: users.label
      validUserRoles:
      menuItems:
        - nameProperty: logIn.label
          path: /login
          validUserRoles:
        - nameProperty: userDetails.label
          path: /userinfo
          validUserRoles:
            - ROLE_USER
            - ROLE_ADMINISTRATOR
        - nameProperty: newUser.label
          path: /newuser
          validUserRoles:
            - ROLE_ADMINISTRATOR
    - nameProperty: cloudServices.label
      validUserRoles:
        - ROLE_USER
        - ROLE_ADMINISTRATOR
      menuItems:
        - nameProperty: list.label
          path: /cloudserviceslist
          validUserRoles:
            - ROLE_USER
            - ROLE_ADMINISTRATOR
        - nameProperty: logIn.label
          path: /cloudserviceslogin
          validUserRoles:
            - ROLE_USER
            - ROLE_ADMINISTRATOR

management.endpoints.web:
  expose: "*"
